---
stages:
  - test
  - build
  - release

include:
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/full-pipeline.yml'
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/release.yml'
