---
stages:
  - test
  - build
  - release
  - deploy

include:
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/full-pipeline.yml'
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/release.yml'

Deploy_Demo:
  stage: deploy
  tags:
    - rc-rdemo
  script: .\PsScripts\deploy.ps1
  environment:
    name: demo
  only:
  when: manual

Deploy_Prod:
  stage: deploy
  tags:
    - rc-r
  script: .\PsScripts\deploy.ps1
  environment:
    name: Prod
  only:
  when: manual



