---
stages:
  - test
  - build
  - release
  - deploy

include:
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/release.yml'

.install_r_package_dev_deps:
  image: rocker/r-ver:4.2.0

  before_script:
    - echo 'INSTALL SYSTEM DEPENDENCIES'
    - apt-get update
    - >
      Rscript -e 'install.packages("pak",
        repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s",
        .Platform$pkgType, R.Version()$os, R.Version()$arch))'
    - Rscript -e 'pak::pak(pkg = "gitcreds")'
    - echo 'SET GIT CREDENTIALS'
    - git config --global credential.helper store
    - >
      echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com"
      > ~/.git-credentials
    - echo 'INSTALL R PACKAGE DEPENDENCIES'
    - >
      echo "options(
        repos = c(
            CRAN = 'https://cloud.r-project.org',
            PPM = 'https://packagemanager.posit.co/cran/__linux__/focal/latest'
          )
        )">>\
         ${R_HOME}/etc/Rprofile.site
    - Rscript -e 'pak::pak(c("MASS@7.3-60.2", "Matrix@1.6-5", "ggplot2@3.5.2"))'
    - Rscript -e 'pak::local_install_dev_deps(upgrade = FALSE)'


pages:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  extends: .install_r_package_dev_deps
  script:
    - echo 'INSTALL R PACKAGE DEPENDENCIES'
    - >
      Rscript -e 'pak::pkg_install(
        c("devtools", "pkgdown"),
        dependencies = TRUE)'
    - echo 'BUILD SITE'
    - Rscript -e 'pkgdown::build_site(lazy = TRUE, preview = FALSE)'
    - mv docs public
  artifacts:
    paths:
      - public


R Package:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  extends: .install_r_package_dev_deps
  script:
    - echo 'INSTALL R PACKAGE DEPENDENCIES'
    - >
      Rscript -e 'pak::pkg_install(c("devtools", "Rcpp", "rcmdcheck"))'
    - echo "BUILD PACKAGE"
    - R CMD build . --no-build-vignettes --no-manual
  artifacts:
    paths:
      - "*.tar.gz"


Check package:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  extends: .install_r_package_dev_deps
  script:
    - echo 'INSTALL R PACKAGE DEPENDENCIES'
    - >
      Rscript -e 'pak::pkg_install(c("devtools", "Rcpp", "rcmdcheck"))'
    - echo "CHECK PACKAGE"
    - >
      Rscript -e 'rcmdcheck::rcmdcheck(
        args = c("--no-manual", "--no-build-vignettes"),
        error_on = "note")'


lint:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  extends: .install_r_package_dev_deps
  variables:
    LINTR_ERROR_ON_LINT: true
  script:
    - >
      Rscript -e 'pak::pkg_install(c("devtools", "lintr"))'
    - echo "Lint package"
    - Rscript -e "devtools::load_all();lintr::lint_package()"


Testthat JUnit report:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  extends: .install_r_package_dev_deps
  script:
    # Install libxt-dev for Cairo R-package
    # that fails to compile otherwise
    - apt-get install -y libxt-dev
    - >
      Rscript -e 'pak::pkg_install(
        c("devtools", "testthat", "covr", "DT", "htmltools"),
        dependencies = TRUE)'
    - echo "Lint package"
    - >
      Rscript -e 'testthat::test_local(
        reporter = testthat::JunitReporter$new(
          file = "../../junit_result.xml"))'
    - Rscript -e 'pak::pkg_install("local::.")'
    - Rscript -e "covr::gitlab(quiet = FALSE)"
  coverage: '/Coverage: \d+\.\d+/'
  artifacts:
    paths:
      - public
    reports:
      junit: junit_result.xml


Deploy_Demo:
  stage: deploy
  tags:
    - rc-rdemo
  script: .\PsScripts\deploy.ps1
  environment:
    name: demo
  only:
  when: manual

Deploy_Prod:
  stage: deploy
  tags:
    - rc-r
  script: .\PsScripts\deploy.ps1
  environment:
    name: Prod
  only:
  when: manual



