---
stages:
  - test
  - release
  - deploy

Lint package:
  stage: test
  variables:
    LINTR_ERROR_ON_LINT: true
  tags:
    - rc-r
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH
  script:
    - RScript.exe -e "devtools::load_all();lintr::lint_package()"

Check package:
  stage: test
  tags:
    - $RUNNER_TAGS
  parallel:
    matrix:
      - RUNNER_TAGS:
        - rc-r
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH
  script:
    - >
      Rscript -e "rcmdcheck::rcmdcheck(
        args = c('--no-manual', '--no-build-vignettes'),
        error_on = 'note')"

Install package:
  stage: deploy
  tags:
    - $RUNNER_TAGS
  parallel:
    matrix:
      - RUNNER_TAGS:
        - rc-rdemo
        - rc-r
  rules:
    # deploy only if on default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
  allow_failure: true
  script:
    - RScript.exe -e "pak::pak('local::.', upgrade = FALSE, dependencies = FALSE)"

check_version_bump:
  image: debian:stable-slim
  stage: test
  rules:
    # Only run on MR to master/main
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
  script:
    - echo "Check that version is bumped before merge to release branch"
    - apt-get update
    - apt-get install -y git
    - git fetch origin $CI_DEFAULT_BRANCH
    - git show origin/$CI_DEFAULT_BRANCH:DESCRIPTION > default_branch_desc
    - echo "$(awk '/Version:/ { print $2 }' DESCRIPTION)" >> version_branch
    - >
      echo "$(awk '/Version:/ { print $2 }' default_branch_desc)" >> \
        version_default_branch
    # Check that versions are different
    - cmp version_branch version_default_branch && exit 1 || echo "Versions are different"
    # Create file with both versions
    # Small version first
    - cat version_default_branch > both_versions
    # branch should be larger version
    - cat version_branch >> both_versions
    # Sort both_versions and check if sorted version is same as original
    - sort --version-sort both_versions | cmp both_versions && echo "Version is increased" || exit 1

get_version:
  image: alpine
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Get version from DESCRIPTION file to use in release and tag"
    - >
      echo "TAG=v$(awk '/Version:/ { print $2 }' DESCRIPTION)" >> \
        variables.env
  artifacts:
    reports:
      dotenv: variables.env

release_job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  needs:
    - job: get_version
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Running release_job for $TAG"
  release:
    tag_name: '$TAG'
    description: 'Automatic tag and release using $TAG'
    ref: '$CI_COMMIT_SHA'

